### ISSUE TITLE
Shell=False problems on windows

### ISSUE THREAD

**Issue by tcoopman** [kennethreitz/envoy#15]
I'm trying envoy on windows7 and have a problem with it.
If I run a command like "dir" I get an error on the line self.returncode = self.process.returncode ("AttributeError: 'NoneType' object has no attribute 'returncode'). This is caused by an WindowsError in the subprocess.Popen call. (WindowsError: [Error 2] The system cannot find the file specified)

After some googling I noticed that the option shell=False causes this problem. When I call subprocess.Popen manually with shell=True, I don't get this error.

More info can be found here: http://bugs.python.org/issue8224
In the bugreport you can see that the conclusion is that this is a windows bug, so they closed the bug as invalid.
But to use envoy on windows, I propose that you check for this, or that you document it somewhere.

I've used the last version of envoy on pypi (0.2), but checked your github code and I suppose that the error is still there.

**Comment by thnee** [comment]
As for `dir`, I am not so sure it's supposed to work as this issue claims, since that is a shell builtin on windows, so `shell=True` is required.

However, this error (`The system cannot find the file specified`) can come up in many other situations. I wanted to run a program, whose path had spaces in it, and pass arguments. I had to create the following workaround, as per this issue: https://github.com/fabric/fabric/issues/258

```
import sys
import envoy
def run(command, *args, **kwargs):
    if sys.platform == 'win32':
        command = [command]
    r = envoy.run(command, *args, **kwargs)
```

Really not sure if I misunderstood something, but at least it works.
